---
version: '3'
vars:
  BIN_DIR: "{{.ROOT_DIR}}/bin"
  BUILD_DIR: "{{.ROOT_DIR}}/build"
tasks:
  build-target:
    dir: "{{.BUILD_DIR}}/"
    cmds:
    - cmake --build . --target {{.TARGET}}
  cmake:configure:
    cmds:
    - cmake --preset={{.CMAKE_PRESET}} {{.ROOT_DIR}}
  configure:
    cmds:
    - task: cmake:configure
      vars:
        CMAKE_PRESET: "{{.CLI_ARGS}}"
  configure:debug:
    cmds:
    - task: cmake:configure
      vars:
        CMAKE_PRESET: "debug"
  build:
    cmds:
    - task: build-target
      vars:
        TARGET: all
  run:
    dir: "{{.BUILD_DIR}}/"
    env:
      MBAR_EXEC: "{{.BUILD_DIR}}/moonbar"
      MBAR_LIB_HOME: "{{.ROOT_DIR}}"
      MBAR_CLIB_HOME: "{{.BUILD_DIR}}/lib"
    cmds:
    - "{{.BIN_DIR}}/run-bar {{.CLI_ARGS}}"
  run:debug:
    dir: "{{.BUILD_DIR}}/"
    env:
      MBAR_EXEC: "{{.BUILD_DIR}}/moonbar"
      MBAR_DEBUG: "lldb"
      MBAR_LIB_HOME: "{{.ROOT_DIR}}"
      MBAR_CLIB_HOME: "{{.BUILD_DIR}}/lib"
    cmds:
    - "{{.BIN_DIR}}/run-bar {{.CLI_ARGS}}"
  clean:
    dir: "{{.BUILD_DIR}}/"
    cmds:
    - task: build-target
      vars:
        TARGET: clean
  default:
    cmds:
    - task: build
